### ISSUE TITLE
pre-final analysis checklist

### ISSUE THREAD

**Issue by jennabraun** [jennabraun/larrea.facilitation#1]
- [x] fill in missing timestamps

- [x] verify species from timestamps

- [x] fill in field of view floral count

produce 2 final cleaned datasets:

- [x] by observation

- [x] by rep (observations aggregated to replicate)
