### ISSUE TITLE
Pre-submission checklist

### ISSUE THREAD

**Issue by jennabraun** [jennabraun/larrea.facilitation#2]
- [x] Chris checks over bootstrapping script (bootallrii.R)

- [x] Clean up appendix

- [x] Submit diversity data to KNB

- [x] Make github webpage for stats complete & also look nice
